name: Publish
on: [push]
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: yarn install --production
    - run: yarn build
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        NODE_ENV: production

    - name: Set CNAME
      run: |
        sudo tee -a public/CNAME > /dev/null << EOF
        quinn.io
        EOF

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
