name: Publish
on: [push]
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install NPM Packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Static Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Set CNAME
      run: |
        ls -lah public
        cat public/CNAME || true
        touch public/index.html || true
        sudo touch public/index.html || true
        sudo tee -a public/CNAME > /dev/null << EOF
        quinnshanahan.com
        EOF
        echo quinnshanahan.com > public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
